version: '3.8'
services:
  backend:
    build: my-doctor-api-swagger/
    depends_on:
      - postgres
    ports:
      - "3091:3091"

  frontend:
    build: myDoctor-web/
    depends_on:
      - backend
    ports:
      - "8080:8080"

  postgres:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "nest"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"

